# Used by Travis CI to run our tests automatically
language: node_js
sudo: false

node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_install:
  # Connect Chromium to run tests in Travis
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - npm install -g yarn
  - yarn install

script:
  - npm run lint
  - npm test
  - npm run build
  - npm run package
